# 1? ??: ?????? ??? ?? ?? ??
spring.application.name=ch4Assignment

# 2? ??: ??? ??? ?? ? ????? ??? ?? ???? ?? (?? H2 ??)
spring.profiles.active=local

# 3? ??: Actuator ???? ????? ?? ? ?? ????? ?? (health ??)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never

# 4? ??: ????? ?? ?? ??? ?????? ?????/???? ?? ??? ???
management.endpoint.health.probes.enabled=true