spring.config.import=aws-parameterstore:/config/ch4Assignment

spring.datasource.url=${spring.datasource.url}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.cloud.aws.region.static=ap-northeast-2

info.team.name=${team-name}
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true