spring:
  application:
    name: ch4Assignment
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true