# 1? ??: AWS Parameter Store(???? ???)??? ?? ???? ?? ?? ?? ??? ??
spring.config.import=aws-parameterstore:/config/ch4Assignment

# 2? ??: ???? ???? ??? ???? ???? ??? ??? RDS MySQL ?? ??
spring.datasource.url=${spring.datasource.url}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

# 3? ??: ?????? JPA? ?????? ??? ???? ? DDL ?? ???? ?? ??
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 4? ??: AWS ??? ??? ?? ?? ?? ?? ?? ??
spring.cloud.aws.region.static=ap-northeast-2

# 5? ??: Actuator ? ????? ?? ?? ? ?? ??? ?? ?? ?? ???
info.team.name=${team-name}
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# 6? ??: ??? ???? ?? ???? ??? S3 ?? ?? ?? ??
aws.s3.bucket=ch4-assignment-jaegu-bucket

# 7? ??: [LV 6] ???? ?? ??? ?? ??? ?? ?? ?? CloudFront ?? ??? ??
aws.cloudfront.domain=https://d33vapcz7o95o.cloudfront.net

# 8? ??: [LV 6] AWS ?? trusted signers ? ??? ?? ??? ?? ??? ? ID
aws.cloudfront.key-pair-id=K1WYOCSTJO21B7

# 9? ??: [LV 6] ???? ??(src/main/resources/certs/)? ???? ?? ??? ???? ? ?? ??
aws.cloudfront.private-key-path=classpath:certs/private_key.pem